services:
  - type: web
    name: laravel-app
    runtime: php
    repo: https://github.com/tu-usuario/tu-repo
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tu-app.onrender.com
      # Otras variables puedes agregarlas en el panel web
